---
name: ZeroTier One
version: dev
slug: zerotier
description: Radically simplify your network with a virtual networking layer that works the same everywhere
url: https://github.com/hassio-addons/addon-zerotier
codenotary: codenotary@frenck.dev
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armv7
ports:
  9993/tcp: 9993
ports_description:
  9993/tcp: ZeroTier's primary port
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
devices:
  - /dev/net/tun
map:
  - ssl:rw
options:
  networks: []
  api_auth_token: ""
  allow_managed: true
  allow_global: false
  allow_default: false
  allow_dns: false
  static_ip: ""
  static_netmask: ""
schema:
  networks:
    - match(^!secret [a-zA-Z0-9_\-]+$|[0-9a-z]{16})
  api_auth_token: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  allow_managed: bool?
  allow_global: bool?
  allow_default: bool?
  allow_dns: bool?
  static_ip: match(^(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$)
  static_netmask: match(^(\b25[0-5]|\b2[0-4][0-9]|\b[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}$)
